# Generated by Django 5.2.15 on 2026-06-25 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_add_showing_task_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowingNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_showing_notes",
                        to="crm.user",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showing_notes",
                        to="crm.property",
                    ),
                ),
                (
                    "showing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_timeline",
                        to="crm.showing",
                    ),
                ),
            ],
            options={
                "db_table": "showing_notes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["showing", "created_at"],
                        name="idx_showing_notes_timeline",
                    ),
                    models.Index(
                        fields=["property"], name="idx_showing_notes_property"
                    ),
                ],
            },
        ),
    ]
